name: vimeo_player_flutter
description: Vimeo Player Flutter package for Flutter apps. Compatible with both iOS and Android platforms.
version: 0.0.3+2
homepage: https://github.com/prahack/vimeo_player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.7.2+3
  path_provider: 2.0.9
  permission_handler: 10.0.2
  url_launcher: 6.1.6
  pointer_interceptor: ^0.9.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
